baseURL        = "https://kentarokuribayashi.com/"
title          = "Kentaro Kuribayashi"
languageCode   = "en-us"
isMultilingual = false
theme          = "sam"

googleAnalytics = "UA-136101963-1"

[params]
  dateform     = "Mon Jan 02, 2006"
  dateformfull = "Mon Jan 2 2006 15:04:05 EST"
  favicon      = "icon.png"
  homepage     = "main"
  footerText   = "Kentaro Kuribayashi's Website"
  description  = "Kentaro Kuribayashi's Website"
  images       = ["icon-192.png"]
  title        = "Kentaro Kuribayashi"

[[params.mainMenu]]
    link = "/about"
    text = "about"

[[params.mainMenu]]
    link = "/posts"
    text = "posts"

[[params.mainMenu]]
    link = "/career"
    text = "career"

# [[params.mainMenu]]
#     link = "/gallery"
#     text = "gallery"

# [[params.mainMenu]]
#     link = "/portfolio"
#     text = "portfolio"

[imaging]
    quality = 100
